name: Release Windows .exe
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: npm ci
      - name: Build web (React)
        run: npm run build
      - name: Package & Publish (electron-builder)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish:win
